name: DifFace
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.9.24=py38h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cudnn=8.2.1=cuda11.3_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1s=h7f8727e_0
  - pip=22.2.2=py38h06a4308_0
  - python=3.8.15=h7a1cb2a_2
  - readline=8.2=h5eee18b_0
  - setuptools=65.5.0=py38h06a4308_0
  - sqlite=3.40.0=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
    - absl-py==1.3.0
    - antlr4-python3-runtime==4.9.3
    - asttokens==2.2.0
    - astunparse==1.6.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - decorator==5.1.1
    - einops==0.6.0
    - executing==1.2.0
    - filelock==3.8.2
    - flatbuffers==22.11.23
    - gast==0.4.0
    - gdown==4.6.0
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.50.0
    - h5py==3.7.0
    - huggingface-hub==0.11.1
    - idna==3.4
    - imageio==2.22.4
    - importlib-metadata==5.1.0
    - ipdb==0.13.9
    - ipython==8.7.0
    - jedi==0.18.2
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - networkx==2.8.8
    - numpy==1.23.5
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - opencv-python==4.5.3.56
    - opt-einsum==3.3.0
    - packaging==21.3
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - prompt-toolkit==3.0.33
    - protobuf==3.19.6
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - pywavelets==1.4.1
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.9.3
    - six==1.16.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.2
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-estimator==2.10.0
    - tensorflow-gpu==2.10.0
    - tensorflow-io-gcs-filesystem==0.28.0
    - termcolor==2.1.1
    - tifffile==2022.10.10
    - timm==0.6.12
    - toml==0.10.2
    - torch==1.12.0
    - torchaudio==0.12.0
    - torchvision==0.13.0
    - tqdm==4.64.1
    - traitlets==5.5.0
    - typing-extensions==4.4.0
    - urllib3==1.26.13
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.11.0
    - kornia
